// The Kotlin plugin is declared here to pin its version in a single place,
// but applied only in the modules that need it.
plugins {
    kotlin("jvm") version "2.4.10" apply false
    id("org.jetbrains.kotlinx.kover") version "0.9.9" apply false
    id("com.google.devtools.ksp") version "2.3.12" apply false
    id("androidx.room") version "2.8.4" apply false
    id("org.jetbrains.kotlin.plugin.serialization") version "2.4.10" apply false
    // AGP 9 ships its own Kotlin support (no longer needs the
    // org.jetbrains.kotlin.android plugin): see https://kotl.in/gradle/agp-built-in-kotlin.
    id("com.android.application") version "9.4.0" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.4.10" apply false
    id("org.jlleitschuh.gradle.ktlint") version "14.2.0"
}

// The style lives in `.editorconfig`, read by ktlint as well as the IDE.
// Applied to all modules: the Kotlin code is split across :engine, :data and :app.
allprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    // ktlint-cli is resolved per project, including at the root, which
    // otherwise has no declared repository.
    repositories {
        mavenCentral()
    }

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set("1.8.0")
        // Code generated by KSP (the Room implementations) is not hand
        // written: the styler would have nothing to say about the repo's code.
        filter {
            exclude { it.file.invariantSeparatorsPath.contains("/build/") }
        }
    }
}
